local ADDON_NAME, namespace = ... 	--localization
local L = namespace.L 				--localization

--local LOCALE = GetLocale()
if namespace.locale == "esES" then
	-- The EU English game client also
	-- uses the US English locale code.

-- ###########################################################################################################################
-- ##	Español (Spanish) translations provided by Tholagar, Mikel391, MrUrkaz, Krounted, and Valhallanem on Curseforge.	##
-- ###########################################################################################################################

L["  /dcstats config: Opens the DejaClassicStats addon config menu."] = "/dcstats config: Abre el menú de configuración de DejaClassicStats"
L["  /dcstats reset:  Resets DejaClassicStats options to default."] = "/dcstats reset: Reinicia DejaClassicStats a los ajustes predeterminados"
L["%s of %s increases %s by %.2f%%"] = "%s de %s incrementa %s en %.2f%%"
L["About DCS"] = "Acerca de DCS"
L["All Stats"] = "Todos los atributos"
L["Attack"] = "Ataque"
L["Average Durability"] = "Durabilidad Media"
L["Average equipped item durability percentage."] = "Porcentaje de durabilidad medio de los objetos equipados."
L["Average Item Level:"] = "Nivel de Objeto medio:"
L["Avoidance Rating"] = "Índice de Elusión"
L["Blizzard's Hide At Zero"] = "Esconder a 0 de Blizzard"
L["Character Stats:"] = "Atributos del personaje:"
L["Class Colors"] = "Color de Clases"
L["Class Crest Background"] = "Fondo del blasón de clase"
L["Critical Strike Rating"] = "Índice de Golpe Crítico"
L["DCS's Hide At Zero"] = "Esconder a Cero de DCS"
L["Decimals"] = "Decimales"
L["Defense"] = "Defensa"
L["Dejablue's improved character stats panel view."] = "Vista mejorada del panel de atributos del personaje por Dejablue."
L["DejaClassicStats Slash commands (/dcstats):"] = "Comandos de barra DejaClassicStats (/dcstats):"
L["Displays a durability bar next to each item."] = "Muestra una barra de durabilidad al lado de cada objeto."
L["Displays average item durability on the character shirt slot and durability frames."] = "Muestra la durabilidad de objeto media en la casilla de camiseta del personaje y en el marco de durabilidad."
L["Displays average item level to one decimal place."] = "Muestra la media de nivel de objeto con un decimal."
L["Displays average item level to two decimal places."] = "Muestra el promedio de nivel de objeto con dos decimales"
L["Displays average item level with class colors."] = "Muestra el nivel de objeto medio con el color de la clase."
L["Displays each equipped item's durability."] = "Muestra la durabilidad de cada objeto equipado."
L["Displays each equipped item's repair cost."] = "Muestra el coste de reparación de cada objeto equipado."
L["Displays 'Enhancements' category stats to two decimal places."] = "Muestra la categoría de 'Mejoras' con dos decimales."
L["Displays Equipped/Available item levels unless equal."] = "Muestra el nivel de objeto Equipado/Disponible a no ser que sean iguales."
L["Displays the class crest background."] = "Muestra el blasón de clase de fondo"
L["Displays the DCS scrollbar."] = "Muestra la barra de desplazamiento de DCS"
L["Displays the Expand button for the character stats frame."] = "Muestra el botón de Expandir en el panel de personaje"
L["Displays the item level of each equipped item."] = "Muestra el nivel de objeto de cada objeto equipado."
L["Dodge Rating"] = "Índice de Esquiva"
L["Durability"] = "Durabilidad"
L["Durability Bars"] = "Barras de Durabilidad"
L["Equipped/Available"] = "Equipado/Disponible"
L["Expand"] = "Expandir"
L["General"] = "General"
L["General global cooldown refresh time."] = "Tiempo de refresco del tiempo de reutilización genérico."
L["Global Cooldown"] = "Reutilización Global"
L["Haste Rating"] = "Índice de Celeridad"
L["Hide Character Stats"] = "Esconder Atributos del Personaje"
--[[Translation missing --]]
--[[ L["Hide low level mastery"] = ""--]] 
L["Hides 'Enhancements' stats if their displayed value would be zero. Checking 'Decimals' changes the displayed value."] = "Oculta las 'Mejoras' de atributos si su valor mostrado debería ser cero. Agregar 'Decimales' cambia el valor mostrado"
L["Hides 'Enhancements' stats only if their numerical value is exactly zero. For example, if stat value is 0.001%, then it would be displayed as 0%."] = "Oculta las 'Mejoras' de atributos solo si su valor numérico es exactamente cero. Por ejemplo, si el valor de atributo es 0.001%, será mostrado como 0%."
--[[Translation missing --]]
--[[ L["Hides Mastery stat until the character starts to have benefit from it. Hiding Mastery with Select-A-Stat™ in the character panel has priority over this setting."] = ""--]] 
L["Item Durability"] = "Durabilidad del Objeto"
L["Item Level"] = "Nivel de Objeto"
L["Item Repair Cost"] = "Coste de Reparación del Objeto"
L["Item Slots:"] = "Ventana del artículo:"
L["Leech Rating"] = "Índice de Restitución"
L["Lock DCS"] = "Bloquear DCS"
L["Main Hand"] = "Mano Derecha"
L["Mastery Rating"] = "Índice de Maestría"
L["Miscellaneous:"] = "Varios:"
L["Movement Speed"] = "Velocidad"
L["Off Hand"] = "Mano Izquierda"
L["Offense"] = "Ofensiva"
L["One Decimal Place"] = "Un decimal"
L["Parry Rating"] = "Índice de Parada"
L["Ratings"] = "Índices"
L["Relevant Stats"] = "Atributos Relevantes"
L["Repair Total"] = "Coste de reparación"
L["Requires Level "] = "Requiere nivel "
L["Reset Stats"] = "Reiniciar Atributos"
L["Reset to Default"] = "Reiniciar a valores por Defecto"
L["Resets order of stats."] = "Reinicia el orden de los atributos"
L["Scrollbar"] = "Barra de desplazamiento"
L["Show all stats."] = "Mostrar todos los Atributos"
L["Show Character Stats"] = "Mostrar todos los Atributos del Personaje"
L["Show only stats relevant to your class spec."] = "Muestra solo atributos relevantes para la especialización de tu clase"
L["Total equipped item repair cost before discounts."] = "Costo total de reparación sin descuentos"
L["Two Decimal Places"] = "Dos decimales"
L["Unlock DCS"] = "Desbloquear DCS"
L["Versatility Rating"] = "Índice de Versatilidad"
L["weapon auto attack (white) DPS."] = "DPS del autoataque (blanco)."
L["Weapon DPS"] = "DPS del Arma"

----------------------------------------------------
-- DejaClassicStats specific translation phrases. --
----------------------------------------------------
L["Primary"] = "Primary"
L["Melee Enhancements"] = "Melee Enhancements"
L["Spell Enhancements"] = "Spell Enhancements"
L["Movement Speed: "] = "Movement Speed: "
L["Durability: "] = "Durability: "
L["Repair Total: "] = "Repair Total: "
L["Melee Crit: "] = "Melee Crit: "
L["Melee Hit: "] = "Melee Hit: "
L["Ranged Crit: "] = "Ranged Crit: "	
L["Melee +Damage: "] = "Melee +Damage: "	
L["Physical Critical Strike: "] = "Physical Critical Strike: "	
L["Dodge: "] = "Dodge: "	
L["Defense: "] = "Defense: "	
L["Parry: "] = "Parry: "	
L["Block: "] = "Block: "	
L["Mana Regen Current: "] = "Mana Regen Current: "	
L["Mana Regen: "] = "Mana Regen: "	
L["MP5: "] = "MP5: "	
L["Spell Crit: "] = "Spell Crit: "	
L["Spell Hit: "] = "Spell Hit: "	
L["Spell +Damage: "] = "Spell +Damage: "	
L["+Healing: "] = "+Healing: "	

L["Darken Item Icons"] = "Darken Item Icons"	
L["Darken item icons to make text more visible."] = "Darken item icons to make text more visible."	
L["Black Item Icons"] = "Black Item Icons"
L["Black item icons to make text more visible."] = "Black item icons to make text more visible."
L["Display Info Beside Items"] = "Display Info Beside Items"
L["Displays the item's info beside each item's slot."] = "Displays the item's info beside each item's slot."
L["Enchants"] = "Enchants"
L["Displays each equipped item's enchantment."] = "Displays each equipped item's enchantment."
L["Background Art"] = "Background Art"
L["Displays the class talents background art."] = "Displays the class talents background art."
L["Monochrome Background Art"] = "Monochrome Background Art"
L["Displays black and white class talents background art."] = "Displays black and white class talents background art."
L["Alternate Expand"] = "Alternate Expand"
L["Displays the Expand button above the hands item slot."] = "Displays the Expand button above the hands item slot."

L["Base Defense including talents such as Warrior's Anticipation is "] = "Base Defense including talents such as Warrior's Anticipation is "
L["Bonus Defense from items and enhancements is "] = "Bonus Defense from items and enhancements is "
L["Total Defense is "] = "Total Defense is "
L[". Critical Hit immunity for a level 60 player against a raid boss occurs at 440 Defense and requires a defense skill of 140 from items and enhancements to achieve."] = ". Critical Hit immunity for a level 60 player against a raid boss occurs at 440 Defense and requires a defense skill of 140 from items and enhancements to achieve."

return end
