local L = LibStub("AceLocale-3.1"):NewLocale("OneCore-1.0", "enUS", true)

--@non-debug@
L["%s collapses all of the related bags into one frame.  In addition to this it provides colored slot highlights, customizable display, behavior enhancements, and more.  In addition plugins can provide a variety of more advanced functionality."] = true
L["Ammo Bags"] = true
L["Ammo Bags & Quivers"] = true
L["Background"] = true
L["Bag Behavior"] = true
L["Bag Centric"] = true
L["Bag Visibility"] = true
L["Clamp to Screen"] = true
L["Color Low Level Items"] = true
L["Color Options"] = true
L["Core Options"] = true
L["Frame Alpha"] = true
L["Frame Behavior"] = true
L["Frame Options"] = true
L["Frame Strata"] = true
L["General"] = true
L["Glow Borders are a little brighter and 'shinier' than the default ones."] = true
L["Item Centric"] = true
L["Lock Frame"] = true
L["Mouseover"] = true
L["Number of Columns"] = true
L["Plugins"] = true
L["Profession Bags"] = true
L["Sets the background color of your bag."] = true
L["Sets the border color of ammo bag slots."] = true
L["Sets the border color of highlighted slots when you mouse over a bag."] = true
L["Sets the border color of profession bag slots."] = true
L["Sets the border color of soul bag slots."] = true
L["Sets the maximum number of columns to use"] = true
L["Soul Bags"] = true
L["There are also many other options available to you in the subpanels.  If you find this addon useful I ask that you tell your friends and give me feedback on how to make it better.  \\n\\nPlease check out the side panel under %s to find all the other options as well as plugin information."] = true
L["There are several customizable colors with regards to your bags.  Each one will control something different."] = true
L["These options affect how the frame itself behaves on your screen."] = true
L["These options affect the way %s works with and treats your bags.  You can use them to do some base customization to the way you view your bags."] = true
L["These options allow you to stop certain bags from displaying."] = true
L["Toggles if a slot's border should be highlighted based on an items rarity."] = true
L["Toggles if the frame is movable or not"] = true
L["Toggles if you can drag the frame off screen."] = true
L["Toggles if you want to color white and grey item's borders as well."] = true
L["Toggles the display of ammo bags and quivers."] = true
L["Toggles the display of profession bags."] = true
L["Toggles the display of soul bags."] = true
L["Type Based Filters"] = true
L["UI Scale"] = true
L["Use Glow Borders"] = true
L["Use Rarity Borders"] = true
L["You can adjust how wide you wish your bag to be.  Note, this is considered a maxinum size.  If you don't have enough slots you will only see as many as you have."] = true
L["You may also adjust some of the characteristics of your bag window.  UI Scale refers to how large the window is while Frame Alpha talks about the overall frame's opacity.  Note that the background transparancy is controlled via the background color."] = true

--@end-non-debug@
